name: Clone PostgreSQL Repository

on:
  schedule:
    - cron: '0 1 * * *'  # Schedule to run at 1 AM UTC

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PostgreSQL Repository
        run: |
          mkdir -p /github/workspace  # Create the directory if needed
          git clone https://git.postgresql.org/git/postgresql.git /github/workspace/postgresql
        shell: /usr/bin/bash

      - name: List Files
        run: |
          ls -la /github/workspace/postgresql
        shell: /usr/bin/bash
