name: Clone PostgreSQL Repository

on:
  push:
  schedule:
    - cron: '0 1 * * *'  # Schedule to run at 1 AM UTC
  workflow_dispatch: # This event trigger allows manual execution

jobs:
  clone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PostgreSQL Repository
        run: |
          mkdir /github/workflow
          git clone https://git.postgresql.org/git/postgresql.git
        working-directory: /github/workflow
